// Code generated by swaggo/swag. DO NOT EDIT.

package api

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "rest.ResponseEnvelope-string": {
                "properties": {
                    "details": {
                        "type": "string"
                    },
                    "request_id": {
                        "example": "669cd40f-ea15-40a8-ab03-81e704a3ecf9",
                        "format": "uuid",
                        "type": "string"
                    },
                    "status": {
                        "$ref": "#/components/schemas/rest.Status"
                    },
                    "status_code": {
                        "example": 200,
                        "type": "integer"
                    }
                },
                "required": [
                    "details",
                    "request_id",
                    "status",
                    "status_code"
                ],
                "type": "object"
            },
            "rest.Status": {
                "enum": [
                    "SUCCESS",
                    "ERROR"
                ],
                "example": "SUCCESS",
                "type": "string",
                "x-enum-varnames": [
                    "StatusSuccess",
                    "StatusError"
                ]
            }
        }
    },
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "Verifies that the service can reach its database.",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "503": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/rest.ResponseEnvelope-string"
                                }
                            }
                        },
                        "description": "Database unavailable"
                    }
                },
                "summary": "Health check",
                "tags": [
                    "health"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "description": "Base path for the app API",
            "url": "/v1"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "App API",
	Description:      "HTTP API for a template application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
